//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhGia()
        {
            this.PhanHoiDanhGias = new HashSet<PhanHoiDanhGia>();
        }
    
        public int MaDG { get; set; }
        public int MaNguoiDung { get; set; }
        public int MaSanPham { get; set; }
        public int MaDonHang { get; set; }
        public Nullable<int> Sao { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDG { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual SanPham SanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanHoiDanhGia> PhanHoiDanhGias { get; set; }
    }
}
