//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanHoiDanhGia
    {
        public int MaPhanHoi { get; set; }
        public int MaDG { get; set; }
        public int MaNguoiDung { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayPhanHoi { get; set; }
    
        public virtual DanhGia DanhGia { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
