//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyQuanAoEntities7 : DbContext
    {
        public QuanLyQuanAoEntities7()
            : base("name=QuanLyQuanAoEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DbSet<DanhGia> DanhGias { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<HinhAnhSanPham> HinhAnhSanPhams { get; set; }
        public virtual DbSet<KhuyenMai> KhuyenMais { get; set; }
        public virtual DbSet<LienHe> LienHes { get; set; }
        public virtual DbSet<MauSac> MauSacs { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<PhanHoiDanhGia> PhanHoiDanhGias { get; set; }
        public virtual DbSet<PhanHoiLienHe> PhanHoiLienHes { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<SanPhamBienThe> SanPhamBienThes { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
    
        public virtual ObjectResult<sp_Contact_GetAll_Result> sp_Contact_GetAll(Nullable<int> maNguoiDung)
        {
            var maNguoiDungParameter = maNguoiDung.HasValue ?
                new ObjectParameter("MaNguoiDung", maNguoiDung) :
                new ObjectParameter("MaNguoiDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Contact_GetAll_Result>("sp_Contact_GetAll", maNguoiDungParameter);
        }
    
        public virtual int sp_Order_Cancel(Nullable<int> maNguoiDung, Nullable<int> maDonHang)
        {
            var maNguoiDungParameter = maNguoiDung.HasValue ?
                new ObjectParameter("MaNguoiDung", maNguoiDung) :
                new ObjectParameter("MaNguoiDung", typeof(int));
    
            var maDonHangParameter = maDonHang.HasValue ?
                new ObjectParameter("MaDonHang", maDonHang) :
                new ObjectParameter("MaDonHang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Order_Cancel", maNguoiDungParameter, maDonHangParameter);
        }
    
        public virtual ObjectResult<sp_Order_GetAll_Result> sp_Order_GetAll(Nullable<int> maNguoiDung)
        {
            var maNguoiDungParameter = maNguoiDung.HasValue ?
                new ObjectParameter("MaNguoiDung", maNguoiDung) :
                new ObjectParameter("MaNguoiDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Order_GetAll_Result>("sp_Order_GetAll", maNguoiDungParameter);
        }
    
        public virtual int sp_Order_UpdateStatus(Nullable<int> maNguoiDung, Nullable<int> maDonHang, string trangThai)
        {
            var maNguoiDungParameter = maNguoiDung.HasValue ?
                new ObjectParameter("MaNguoiDung", maNguoiDung) :
                new ObjectParameter("MaNguoiDung", typeof(int));
    
            var maDonHangParameter = maDonHang.HasValue ?
                new ObjectParameter("MaDonHang", maDonHang) :
                new ObjectParameter("MaDonHang", typeof(int));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Order_UpdateStatus", maNguoiDungParameter, maDonHangParameter, trangThaiParameter);
        }
    
        public virtual int sp_Product_Delete(Nullable<int> maNguoiDung, Nullable<int> maSanPham)
        {
            var maNguoiDungParameter = maNguoiDung.HasValue ?
                new ObjectParameter("MaNguoiDung", maNguoiDung) :
                new ObjectParameter("MaNguoiDung", typeof(int));
    
            var maSanPhamParameter = maSanPham.HasValue ?
                new ObjectParameter("MaSanPham", maSanPham) :
                new ObjectParameter("MaSanPham", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_Delete", maNguoiDungParameter, maSanPhamParameter);
        }
    
        public virtual int sp_Product_Insert(Nullable<int> maNguoiDung, string tenSanPham, Nullable<int> maDanhMuc, Nullable<decimal> gia, Nullable<int> soLuongTon, string moTa, string hinhAnhChinh)
        {
            var maNguoiDungParameter = maNguoiDung.HasValue ?
                new ObjectParameter("MaNguoiDung", maNguoiDung) :
                new ObjectParameter("MaNguoiDung", typeof(int));
    
            var tenSanPhamParameter = tenSanPham != null ?
                new ObjectParameter("TenSanPham", tenSanPham) :
                new ObjectParameter("TenSanPham", typeof(string));
    
            var maDanhMucParameter = maDanhMuc.HasValue ?
                new ObjectParameter("MaDanhMuc", maDanhMuc) :
                new ObjectParameter("MaDanhMuc", typeof(int));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("Gia", gia) :
                new ObjectParameter("Gia", typeof(decimal));
    
            var soLuongTonParameter = soLuongTon.HasValue ?
                new ObjectParameter("SoLuongTon", soLuongTon) :
                new ObjectParameter("SoLuongTon", typeof(int));
    
            var moTaParameter = moTa != null ?
                new ObjectParameter("MoTa", moTa) :
                new ObjectParameter("MoTa", typeof(string));
    
            var hinhAnhChinhParameter = hinhAnhChinh != null ?
                new ObjectParameter("HinhAnhChinh", hinhAnhChinh) :
                new ObjectParameter("HinhAnhChinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_Insert", maNguoiDungParameter, tenSanPhamParameter, maDanhMucParameter, giaParameter, soLuongTonParameter, moTaParameter, hinhAnhChinhParameter);
        }
    
        public virtual int sp_Product_Update(Nullable<int> maNguoiDung, Nullable<int> maSanPham, string tenSanPham, Nullable<int> maDanhMuc, Nullable<decimal> gia, Nullable<int> soLuongTon, string moTa, string hinhAnhChinh)
        {
            var maNguoiDungParameter = maNguoiDung.HasValue ?
                new ObjectParameter("MaNguoiDung", maNguoiDung) :
                new ObjectParameter("MaNguoiDung", typeof(int));
    
            var maSanPhamParameter = maSanPham.HasValue ?
                new ObjectParameter("MaSanPham", maSanPham) :
                new ObjectParameter("MaSanPham", typeof(int));
    
            var tenSanPhamParameter = tenSanPham != null ?
                new ObjectParameter("TenSanPham", tenSanPham) :
                new ObjectParameter("TenSanPham", typeof(string));
    
            var maDanhMucParameter = maDanhMuc.HasValue ?
                new ObjectParameter("MaDanhMuc", maDanhMuc) :
                new ObjectParameter("MaDanhMuc", typeof(int));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("Gia", gia) :
                new ObjectParameter("Gia", typeof(decimal));
    
            var soLuongTonParameter = soLuongTon.HasValue ?
                new ObjectParameter("SoLuongTon", soLuongTon) :
                new ObjectParameter("SoLuongTon", typeof(int));
    
            var moTaParameter = moTa != null ?
                new ObjectParameter("MoTa", moTa) :
                new ObjectParameter("MoTa", typeof(string));
    
            var hinhAnhChinhParameter = hinhAnhChinh != null ?
                new ObjectParameter("HinhAnhChinh", hinhAnhChinh) :
                new ObjectParameter("HinhAnhChinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_Update", maNguoiDungParameter, maSanPhamParameter, tenSanPhamParameter, maDanhMucParameter, giaParameter, soLuongTonParameter, moTaParameter, hinhAnhChinhParameter);
        }
    }
}
