//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamBienThe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPhamBienThe()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
    
        public int MaBienThe { get; set; }
        public int MaSanPham { get; set; }
        public int MaSize { get; set; }
        public int MaMau { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual MauSac MauSac { get; set; }
        public virtual SanPham SanPham { get; set; }
        public virtual Size Size { get; set; }
    }
}
